---
deployment:
  tasks:
    - |
      # Define o caminho de destino do tema WordPress
      # IMPORTANTE: Se o repositório já está na pasta do tema, este script apenas ajusta permissões
      # Se o repositório está em outro local, descomente e ajuste a linha DEPLOYPATH abaixo
      
      # Se o repositório NÃO está na pasta do tema, descomente e ajuste:
      # DEPLOYPATH="/home/$USER/public_html/wp-content/themes/cbd-ai-theme"
      # mkdir -p "$DEPLOYPATH"
      # /bin/cp -R * "$DEPLOYPATH/" 2>/dev/null || true
      
      # Ajusta permissões: 755 para diretórios, 644 para arquivos
      find . -type d -not -path './.git*' -exec chmod 755 {} \;
      find . -type f -not -path './.git*' -exec chmod 644 {} \;
      
      # Garante que arquivos executáveis tenham permissão correta
      find . -name "*.sh" -exec chmod 755 {} \; 2>/dev/null || true

