---
deployment:
  tasks:
    - /bin/bash -c 'REPO_DIR=$(pwd); TARGET_THEME="$HOME/public_html/wp-content/themes/cbd-ai-theme"; rm -rf "$TARGET_THEME"; mkdir -p "$HOME/public_html/wp-content/themes"; if [ -d "$REPO_DIR/app/public/wp-content/themes/cbd-ai-theme" ]; then cp -R "$REPO_DIR/app/public/wp-content/themes/cbd-ai-theme" "$HOME/public_html/wp-content/themes/"; elif [ -d "$REPO_DIR/wp-content/themes/cbd-ai-theme" ]; then cp -R "$REPO_DIR/wp-content/themes/cbd-ai-theme" "$HOME/public_html/wp-content/themes/"; fi; chmod -R 755 "$TARGET_THEME"; find "$TARGET_THEME" -type f -exec chmod 644 {} \;'
    - /bin/bash -c 'if [ -d "$HOME/public_html/app" ]; then rm -rf "$HOME/public_html/app"; fi'
    - /bin/bash -c 'if [ -f "$HOME/public_html/deploy.sh" ]; then rm -f "$HOME/public_html/deploy.sh"; fi'
    - /bin/bash -c 'if [ -d "$HOME/public_html/.git" ]; then rm -rf "$HOME/public_html/.git"; fi'
    - /bin/bash -c 'if [ -f "$HOME/public_html/.gitignore" ]; then rm -f "$HOME/public_html/.gitignore"; fi'
    - /bin/bash -c 'if [ -f "$HOME/public_html/.cpanel.yml" ]; then rm -f "$HOME/public_html/.cpanel.yml"; fi'
