---
deployment:
  tasks:
    - /bin/mkdir -p $HOME/public_html/wp-content/themes/cbd-ai-theme
    - /bin/cp -R app/public/wp-content/themes/cbd-ai-theme/. $HOME/public_html/wp-content/themes/cbd-ai-theme/
    - /bin/chmod -R 755 $HOME/public_html/wp-content/themes/cbd-ai-theme
