---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/wp-content/themes
    - export REPO_ROOT=$(pwd)
    - /bin/rm -rf $DEPLOYPATH/cbd-ai-theme
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R $REPO_ROOT $DEPLOYPATH/cbd-ai-theme
    - /bin/rm -rf $DEPLOYPATH/cbd-ai-theme/.git
    - /bin/rm -f $DEPLOYPATH/cbd-ai-theme/.gitignore
    - /bin/rm -f $DEPLOYPATH/cbd-ai-theme/.cpanel.yml
    - /bin/chmod -R 755 $DEPLOYPATH/cbd-ai-theme
    - /bin/find $DEPLOYPATH/cbd-ai-theme -type f -exec chmod 644 {} \;
