---
deployment:
  tasks:
    - export DEPLOY_PATH=$HOME/public_html
    - mkdir -p $DEPLOY_PATH/wp-content/themes
    - /bin/cp -R app/public/wp-content/themes/cbd-ai-theme $DEPLOY_PATH/wp-content/themes/
