---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/wp-content/themes
    - /bin/rm -rf $DEPLOYPATH/cbd-ai-theme
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R app/public/wp-content/themes/cbd-ai-theme $DEPLOYPATH/
    - /bin/chmod -R 755 $DEPLOYPATH/cbd-ai-theme
    - /bin/find $DEPLOYPATH/cbd-ai-theme -type f -exec chmod 644 {} \;
